/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iphone_17_promax_orange.glb --transform 
Files: iphone_17_promax_orange.glb [5.99MB] > /Users/mac/Desktop/AppleWeb/frontend/public/models/iphone_17_promax_orange-transformed.glb [508.33KB] (92%)
Author: TechFreak (https://sketchfab.com/Tech_Freak-2511)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-17-pro-max-cosmic-orange-1b9ed381921445a08f5c75d79f21b23c
Title: Iphone 17 pro max cosmic orange
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iphone_17_promax_orange-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial001} position={[-0.025, 0.044, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.YVjGRIfwSbFphGH} position={[0.007, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.iAKEWdNafBldSCV} position={[0.039, -0.033, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial002} position={[0, -0.004, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.025, 0.064, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.SLmJkLdkhbbuEfG} position={[0.025, 0.045, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.EOPlztmjOhyFwUF} position={[0.007, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.EiHyBykxPjKZBgf} position={[-0.025, 0.064, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.SMUhrjUPCjJkPUK} position={[0, -0.026, -0.013]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.BsXHDwLKqtDOfrW} position={[0, 0.002, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.NUlImpGytyodpBy} position={[0.025, 0.064, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.PaletteMaterial003} position={[-0.001, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.UiBplfShRNPzcmF} position={[-0.025, 0.064, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.PaletteMaterial004} position={[0.007, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.AYSuIKiLIvlGvvQ} position={[0.025, 0.064, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.PaletteMaterial005} position={[0.025, 0.064, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.VXTclbUnoLmmPoD} position={[0, -0.084, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_111.geometry} material={materials.YQFhPSFSryEqJMp} position={[0, -0.084, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_123.geometry} material={materials.hqDUrVMlYhzYusu} position={[-0.025, 0.064, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_133.geometry} material={materials.PaletteMaterial006} position={[0, -0.024, -0.013]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_141.geometry} material={materials.PJgHvfOhNXkxvzq} position={[0.039, -0.033, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_145.geometry} material={materials.PaletteMaterial007} position={[0, -0.025, -0.013]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_157.geometry} material={materials.HETovHCBsEjcSiP} position={[0, -0.084, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/iphone_17_promax_orange-transformed.glb')
