/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iphone_17_promax_grey.glb --transform 
Files: iphone_17_promax_grey.glb [2.28MB] > /Users/mac/Desktop/AppleWeb/frontend/public/models/iphone_17_promax_grey-transformed.glb [148.45KB] (93%)
Author: umutbekdemir2025 (https://sketchfab.com/umutbekdemir2025)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/iphone-17-promax-39ee802bad0d4e878683262c637e8f85
Title: İPhone 17 promax
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iphone_17_promax_grey-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_0.geometry} material={materials.PaletteMaterial001} scale={9.22} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial002} scale={9.22} />
    </group>
  )
}

useGLTF.preload('/iphone_17_promax_grey-transformed.glb')
