/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iphone17_promax_deepblue_fix.glb --transform 
Files: iphone17_promax_deepblue_fix.glb [819.57KB] > /Users/mac/Desktop/AppleWeb/frontend/public/models/iphone17_promax_deepblue_fix-transformed.glb [100.37KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iphone17_promax_deepblue_fix-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_44.geometry} material={materials.PaletteMaterial001} position={[-0.004, -0.002, -0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.PaletteMaterial002} position={[-0.004, 0, -0.001]} rotation={[Math.PI, 0, Math.PI]} scale={0.1} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.Setka} position={[-0.004, 0, -0.001]} rotation={[Math.PI, 0, Math.PI]} scale={0.1} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.Screen} position={[-0.004, 0, -0.001]} rotation={[Math.PI, 0, Math.PI]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/iphone17_promax_deepblue_fix-transformed.glb')
